Location.destroy_all 

locations = Location.create([
{name:'Autry National Center of the American West (in Griffith Park)',
 address:'4700 Western Heritage Way, Los Angeles, CA 90027', 
 description:"Spacious museum featuring exhibits with artwork & artifacts, plus a cafe & children's activities.", 
 website:'theautry.org/', 
 phone:'(323) 667-2000', 
 free_parking:'0', 
 parking_notes:'FREE parking at 4700 Western Heritage Way, directly in front of the Autry.', 
 tours:'', 
 direction_notes:'Located within Griffith Park.', 
 special_closure:'', 
 event_notes:''},

{name:'California Science Center',
 address:'700 Exposition Park Dr, Los Angeles, CA 90037', 
  description:"Through hands-on experiences in the galleries at the California Science Center, you'll learn about human inventions and innovations, the processes of living things and more. Be sure to check out the newly opened aquarium!",
   website:'www.californiasciencecenter.org/',
    phone:'(323) 724-3623',
     free_parking:'1' ,
     parking_notes:"Parking is $10 for cars and yellow school buses, and $25 for Charter buses and oversize vehicles (cash only). To reach the parking structure, turn west into Exposition Park on 39th Street from Figueroa and follow the signs.",
      tours:'', 
      direction_notes:"South of downtown Los Angeles, the California Science Center is located in historic Exposition Park, just two blocks west of the Harbor (110) Freeway at the Exposition Boulevard exit.", 
      special_closure:"Closed Thanksgiving, Christmas and New Year's Day",
      event_notes:'',
 },

{name:'California African American Museum',
 address:'600 State Dr, Los Angeles, CA 90037', 
  description:"The California African American Museum’s exhibitions enhance public knowledge of African American contributions to society.",
   website:'www.caamuseum.org',
    phone:'(213) 744-7432',
     free_parking:'1' ,
      parking_notes:"Parking is $10 (entrance at 39th & Figueroa)",
       tours:'', 
       direction_notes:'', 
       special_closure:'',
       event_notes:'',
   },

{name: "Craft & Folk Art Museum",
 address:'5814 Wilshire Blvd, Los Angeles, CA 90036' , 
  description:"The Craft & Folk Art Museum engages people through its diverse exhibitions and programs that challenge established ideas about craft and folk art and inspire a sense of inquiry and creativity within all people. Serving Los Angeles for over forty years in the city’s historic Miracle Mile district, the Craft & Folk Art Museum is the only institution in Los Angeles exclusively dedicated to celebrat­ing contemporary and traditional craft and folk art." ,
   website:'www.cafam.org/',
    phone:'(323) 937-4230',
     free_parking:'1' ,
      parking_notes:"There are three large public parking lots within a block of CAFAM as well as two hour street parking. CAFAM does not validate for public lots.",
       tours:'',
        direction_notes:'',
         special_closure:'',
       event_notes:'',
   },

{name:'Dominguez Rancho Adobe Museum', 
  address:'18127 S Alameda St, Compton, CA 90220', 
  description:"The Dominguez Rancho Adobe is California Historical Landmark Number 152, and in 1976 was placed on the National Register of Historic Places by the United States Department of the Interior.",
   website:'dominguezrancho.org/',
    phone:'(310) 603-0088',
     free_parking:'1' ,
      parking_notes:"Free street parking on Vermont. Parking for the Museum is also located around the rose garden. Please park your car head first into the spaces around the rose garden only. Parking is not permitted in front of the 2-story retirement home. For special events, parking will be on the lower grounds and the upper grounds will be reserved for handicapped parking.",
       tours:"1pm, 2pm, 3pm on Wednesday, Saturday, and Sunday. 1pm, 2pm, 3pm the first Thursday and Friday of each month. Garden
       Tours: 11 am, 4th Saturday of the month. Spanish
       tours: 11 am, 2nd Sunday of the month.",
       direction_notes:'',
        special_closure:'',
       event_notes:'',
   },

{name:'UCLA Fowler Museum',
 address:'308 Charles E Young Dr N, Los Angeles, CA 90024', 
  description:"Exhibitions from Africa, Asia, the Pacific and the Americas, past and present, lend a unique and intriguing atmosphere to Fowler Museum events.",
   website:'http://www.fowler.ucla.edu/visit',
    phone:'(310) 825-4361',
     free_parking:'1',
      parking_notes:"Easy self-service, Pay-By-Space parking is available near the Museum. Enter UCLA campus Lot 4 from Sunset Blvd. at Westwood Plaza and turn left into the Pay-By-Space area of the lot. The parking fee is a maximum of $12 for the whole day. One hour parking costs $3, 1.5 hours is $4, and two hours is $6.",
       tours:'',
       direction_notes:' Located at UCLA.',
        special_closure:'',
       event_notes:'',

   },

{name:'Griffith Observatory',
 address:'2800 E Observatory Rd, Los Angeles, CA 90027', 
  description:"Griffith Observatory sits on the south-facing slope of Mount Hollywood in Los Angeles Griffith Park. The Observatory offers one of the best views of LA. There is also a free space museum inside.",
   website:'www.griffithobs.org/',
    phone:'(213) 473-0800',
     free_parking:'0',
      parking_notes:"FREE PARKING! Visitors may drive directly to Griffith Observatory and park in its parking lot or on the adjacent roads.",
       tours:'',
       direction_notes:"Visitors may approach the Observatory via the Vermont or Fern Dell entrances to Griffith Park (see map below). Please note that access via Fern Dell closes each evening at sunset.",
        special_closure:'',
       event_notes:'',
   },

{name:'J. Paul Getty Museum',
 address:'1200 Getty Center Dr, Los Angeles, CA 90049', 
  description:"Overlooking the California coastline and the L.A. skyline, the Getty Center surrounds guests with breathtaking views and a world-class art collection including European paintings, contemporary photographs and decorative arts. The magnificent Malibu property, the Getty Villa, includes an educational center and museum dedicated to the study of the arts and cultures of ancient Greece, Rome and Etruria.",
   website:'https://www.getty.edu/visit/',
    phone:'(310) 440-7300',
     free_parking:'1' ,
      parking_notes:"$15; $10 after 5:00 p.m.",
       tours:"GARDEN TOURS (45 min): 11:30 am, 12:30 pm, 2:30 pm, 3:30 pm daily. ARCHITECTURE TOURS (45 min): 10:15 am, 11 am, 1 pm, 2 pm, 3 pm, 4 pm daily. ART TOURS (1 hr): 11 am, 12:30 pm. Please see website for most updated information & where to meet the tour guide. http://www.getty.edu/visit/cal/",
       direction_notes:'',
        special_closure:'',
       event_notes:'',
   },

{name:'J. Paul Getty Villa',
 address:'17985 Pacific Coast Hwy, Pacific Palisades, CA 90272', 
  description:"Overlooking the California coastline and the L.A. skyline, the Getty Center surrounds guests with breathtaking views and a world-class art collection including European paintings, contemporary photographs and decorative arts. The magnificent Malibu property, the Getty Villa, includes an educational center and museum dedicated to the study of the arts and cultures of ancient Greece, Rome and Etruria.",
   website:'www.getty.edu/visit/villa/',
    phone:'(310) 440-7300',
     free_parking:'1',
      parking_notes:"$15; $10 after 5:00 p.m.",
       tours:'',
       direction_notes:'',
        special_closure:" Closed (yr 2014): January 1, August 27, September 3, September 17, September 24, Thanksgiving, and December 25",
       event_notes:'',
   },

{name:'UCLA Hammer Museum',
 address:'10899 Wilshire Blvd, Los Angeles, CA 90024', 
  description:"This magnificent Malibu property includes an educational center and museum dedicated to the study of the arts and cultures of ancient Greece, Rome and Etruria.",
   website:'hammer.ucla.edu' ,
    phone:'(310) 443-7000',
     free_parking:'1',
      parking_notes:"Parking is available under the Museum. Rates are $3 for the first three hours with validation, and $1.50 for each additional 15 minutes. There is a $3 flat rate after 6pm on weekdays, and all day on Saturdays and Sundays. Parking for people with disabilities is provided on levels P1 and P3. Bicycles park free.",
       tours:'',
       direction_notes: "The Museum is located at the northeast corner of Westwood Boulevard and Wilshire Boulevard in Westwood Village, three blocks east of the 405 freeway's Wilshire exit.",
        special_closure:'Closed: January 1,  July 4, Thanksgiving, December 25',
       event_notes:'',
 },

{name:'The Huntington Library, Art Collections, and Botanical Gardens',
 address:'1151 Oxford Rd, San Marino, CA 91108', 
  description:"Expansive complex housing art galleries with famous works, rare-book collections & lush gardens. PLEASE NOTE: Free admission is limited, so reserve your ticket ahead of time. Tickets are free and can be requested online or by calling our ticketing agency at 800-838-3006. You may choose from two arrival times: morning (10:30 a.m.) or afternoon (1:30 p.m.) below. A limited quantity will be available the first day of each month at 9 a.m. preceding the month you wish to visit. (For example, if you wish to visit on August Free Day, you may call for tickets beginning July 1). Please note that Free Day tickets are not available at The Huntington, and may only be reserved by phone or online. You may not purchase regular admission tickets on Free Day.",
   website:"http://www.huntington.org/WebAssets/Templates/content.aspx?id=844" ,
    phone:'(626) 405-2100',
     free_parking:'0',
      parking_notes:'FREE parking available.',
       tours:'',
       direction_notes:"The Huntington is located near Pasadena in the city of San Marino, twelve miles northeast of downtown Los Angeles. The Huntington has two entrance gates: at Allen Avenue, just south of California Boulevard, and on Oxford Road.",
        special_closure:'', 
        event_notes:'Recommended to reserve tickets ahead of time.',
   },

{name:'Japanese American National Museum',
 address:'100 N Central Ave, Los Angeles, CA 90012', 
  description:'The Japanese American National Museum is a museum dedicated to preserving the history and culture of Japanese Americans. It is located in the Little Tokyo area near downtown LA.' ,
   website:'www.janm.org/' ,
    phone:'(213) 625-0414',
     free_parking:'1',
      parking_notes:'Street parking recommended.',
       tours:'',
       direction_notes:' Located in Little Tokyo.',
        special_closure:' ',
       event_notes:'',
   },
{name:'LACMA',
 address:'5905 Wilshire Blvd, Los Angeles, CA 90036', 
  description:"The LACMA is one of the largest art museums in LA.",
   website:'lacma.org',
    phone:'(323) 857-6000',
     free_parking:'1' ,
      parking_notes:"Street parking available north and south of the museum. LACMAs parking is located at the Pritzker Parking Garage on Sixth St, just east of Fairfax Ave, and on the corner of Wilshire Blvd at Spaulding Ave. The $10 charge may be prepaid at the ticket office. Parking is free after 7 pm entry.",
       tours:' ',
       direction_notes:'From the Santa Monica Freeway (10), take Fairfax Avenue north 2 miles to Wilshire Boulevard.',
        special_closure:'Free also on select federal holidays', event_notes:'Need valid LA county museum. Free for children 17 and under.',
   },

{name:'Los Angeles Museum of the Holocaust',
 address:'100 S The Grove Dr, Los Angeles, CA 90036', 
  description:"LAMH dedicates itself as a primary-source institution, one that commemorates those who perished and those who survived the Holocaust, by housing the precious artifacts that miraculously weathered the war, the ghettos and ultimately, the death camps.",
   website:'www.lamoth.org/',
    phone:'(323) 651-3704',
     free_parking:'0' ,
      parking_notes:"FREE parking available in the Museum's underground parking lot, accessible from The Grove Drive. Visitors must announce their wish to park using the intercom at the driveway. Please be prepared to open your trunk and show I.D. Parking is for Museum visitors only. Visitors to the Museum may also park in the Pan Pacific Park lot at 7600 Beverly Blvd. and access the Museum from the Park. Weekend overflow parking may be directed to parking at CBS. Parking is also available in the pay parking structure at The Grove.",
       tours:'',
       direction_notes:'LOCATED IN PAN PACIFIC PARK NEAR THE GROVE AND FARMERS MARKET.',
        special_closure:'',
       event_notes:'',
   },

{name:'Museum of Contemporary Art, Los Angeles',
 address:'250 S Grand Ave, Los Angeles, CA 90012', 
  description:"An airy space showcasing masters in Pop Art & abstract expressionism as well as emerging artists.",
   website:'moca.org',
    phone:'(213) 626-6222',
     free_parking:'1' ,
      parking_notes:"Street parking recommended. Parking also available through the Walt Disney Concert Hall garage, enter from Lower Grand Avenue or 2nd Street.  $9 flat rate with MOCA validation ($20 deposit required upon entry; $11 refund). (Price subject to change.)",
       tours:'',
       direction_notes:'',
        special_closure:'',
       event_notes:'',
   },

{name:'Natural History Museum of Los Angeles County',
 address:'900 Exposition Blvd, Los Angeles, CA 90007', 
  description:'The Natural History Museum of Los Angeles County is the largest natural and historical museum in the western United States, and its collections include nearly 35 million specimens and artifacts and cover 4.5 billion years of history.',
   website:'www.nhm.org/',
    phone:'(213) 763-3466',
     free_parking:'1',
      parking_notes:"Parking is available for $10 in the Museum’s Car Park on Exposition Blvd. and Bill Robertson Lane. If the Car Park is full, patrolled lots are also available directly across from the Museum on Bill Robertson Lane for $10 (cash only), as well as in lots throughout Exposition Park. Parking rates and availability may vary during special events in Exposition Park. NHM has designated parking during USC games.",
       tours:'',
       direction_notes:'The Natural History Museum is located in Exposition Park at 900 Exposition Boulevard between Vermont Avenue and Figueroa Street. Just south of USC campus.',
        special_closure:'Not free in July & August',
       event_notes:'',
   },

{name:'Norton Simon Museum',
 address:'411 W Colorado Blvd, Pasadena, CA 91105', 
  description:"The Norton Simon Museum is an art museum located in Pasadena. Be sure to check out the garden!",
   website:'www.nortonsimon.org/',
    phone:'(626) 449-6840',
     free_parking:'0' ,
      parking_notes:'FREE parking available at the museum.' ,
       tours:'',
       direction_notes:"The Museum is located at 411 W. Colorado Blvd. in Pasadena on the corner of Orange Grove and Colorado Boulevard at the intersection of the Foothill (210) and Ventura (134) freeway.",
        special_closure:'',
       event_notes:'',
   },

{name:'USC Pacific Asia Museum',
 address:'46 N Los Robles Ave, Pasadena, CA 91101', 
  description:"The Pacific Asia Museum showcases Asian art and has a beautiful garden. Established in 1971, the museum is one of few U.S. institutions dedicated to the arts and culture of Asia and the Pacific Islands.",
   website:'www.pacificasiamuseum.org/',
    phone:'(626) 449-2742',
     free_parking:'0',
      parking_notes:'FREE parking is available in the USC Pacific Asia Museum parking lot on the corner of Los Robles Avenue and Union Street, directly north of the museum.',
       tours:'',
       direction_notes:'',
        special_closure:'', event_notes:' '
   },

{name:'Page Museum La Brea Tar Pits',
 address:'5801 Wilshire Blvd, Los Angeles, CA 90036', 
  description:'EXPLORE THE PARK, THE BUBBLING ASPHALT PITS, AND THE EXCAVATION SITES.  THEN COME INSIDE THE PAGE MUSEUM TO SEE WHAT WE DO WITH ALL THE FOSSILS WE FIND!',
   website:'www.tarpits.org/',
    phone:'(323) 934-7243',
     free_parking:'1',
      parking_notes:"Street parking available. If you choose street parking, please read all parking signs carefully, as restrictions apply.  Most importantly, DO NOT PARK ALONG WILSHIRE BOULEVARD between the hours of 7-9 am and 4-7 pm (Monday - Friday), or your car will be ticketed and towed.  This applies even if you are parked at a meter.Parking at the museum is $9 flat rate. The Museum's parking lot is located at the corner of Curson Ave. and 6th St., directly behind the museum (enter from the western side of Curson Ave).",
       tours:'Weekdays: 1 pm - 3 pm. Saturdays and Sundays: 12 pm, 2 pm, and 3 pm. Start inside, then explore Museum or Hancock Park.',
       direction_notes:'',
        special_closure:'Not free in July & August.',
       event_notes:'',
   },

{name:'Santa Monica Museum of Art',
 address:'Building G1, 2525 Michigan Ave, Santa Monica, CA 90404', 
  description:'The Santa Monica Museum of Art organizes dynamic exhibitions of contemporary art in all mediums and across disciplines, complemented by outstanding educational programs for people of all ages.',
   website:'https://smmoa.org/',
    phone:'(310) 586-6488',
     free_parking:'0',
      parking_notes:'FREE parking for museum visitors is available in the Bergamot Station Arts Center parking lot and along Michigan Avenue.',
       tours:'',
       direction_notes:'',
        special_closure:'', event_notes:' '
   },

{name:'Travel Town Museum',
 address:'5200 Zoo Dr, Los Angeles, CA 90027', 
  description:'Located in Griffith Park, this museum is dedicated to the preservation and celebration of railroading in the western United States, featuring displays of historic steam locomotives, passenger cars and trolleys.',
   website:'www.traveltown.org/',
    phone:'(323) 662-9678',
     free_parking:'0',
      parking_notes:"FREE parking available in Griffith Park.",
       tours:'',
       direction_notes:"Just 12 miles north of Downtown in beautiful Griffith Park, we're next to the 134 Freeway at the Forest Lawn Drive exit.",
        special_closure:'', event_notes:'$2.75 to ride a train'
   },

{name:'USC Fisher Museum of Art',
 address:'823 W Exposition Blvd, Los Angeles, CA 90089', 
  description:'Located on the USC Campus',
   website:'fisher.usc.edu/',
    phone:'(213) 740-4561',
     free_parking:'0',
      parking_notes:"Street parking recommended north of campus. For public parking on USC campus, enter campus at Exposition Blvd. and Watt Way. Inquire with attendant for directions to closest parking facility.",
       tours:'',
       direction_notes:'The USC Fisher Museum of Art is located on the south side of the USC campus, bordering Exposition Boulevard, between Figueroa and Watt Way in Harris Hall.',
        special_closure:'', event_notes:' '
   },

{name:'UCLA Meteorite Gallery',
 address:'595 Charles E. Young Dr, East, Los Angeles, CA, 90095', 
  description:'The UCLA Collection of Meteorites is the largest on the West Coast and contains over 2400 samples from about 1400 different meteorites. One or more tour guides are present on Sundays!' ,
   website:'www.meteorites.ucla.edu/',
    phone:'n/a',
     free_parking:'1',
      parking_notes:'It is difficult to find free parking but weekend and evening rates in pay-by-space areas in Lot 2 (the rose rectangle just east of the Geology Building) are very reasonable: $2 for one hour, $4 for two hours, and $8 for one day (rates on work days are 50% higher). You can pay with a credit card or dollar bills. there are several entrances to Lot 2; the one for pay-by-space is shown on the map just west of the number 2 in a white circle.',
       tours:'',
       direction_notes:'Located on the east side of the UCLA campus. (room 3697 of the Geology Building)',
        special_closure:'',
       event_notes:'',
   },

{name:'Banning Residence Museum',
 address:'401 E M St, Wilmington, CA 90744', 
  description:'The 1864 Greek Revival residence, the Banning Residence Museum, is the former home of General Phineas Banning, the "father" of the Los Angeles Harbor.',
   website:'www.banningmuseum.org/',
    phone:'(310) 548-7777',
     free_parking:'1',
      parking_notes:'Street parking is available on M Street and North Banning Boulevard.',
       tours:'Tuesday – Thursday: 12:30, 1:30, 2:30. Saturday – Sunday: 12:30, 1:30, 2:30, 3:30',
       direction_notes:'The Banning Estate is located near the Banning/Wrigley Historic Preservation Overlay Zone in Wilmington.',
        special_closure:'',
       event_notes:'',
   },

{name:'Hollywood Bowl Museum',
 address:'2301 N Highland Ave, Los Angeles, CA 90068', 
  description:"Located on the grounds of the iconic venue, this museum houses the Hollywood Bowl Hall of Fame and also highlights great moments in classical and Latin music, jazz and rock & roll. Families may visit the museum during the museum's public hours without appointment. The exhibits are very kid-friendly, and interactive, with music-making, computers, earphones to listen to music, slideshows, movies, TV shows, and cartoons featuring the Hollywood Bowl. You may also walk up Peppertree Lane and visit the Bowl year-round. On most summer mornings, you are welcome to bring children into the Bowl to listen to a rehearsal.",
   website:'http://www.hollywoodbowl.com/visit/hollywood-bowl-museum',
    phone:'(323) 850-2000',
     free_parking:'0',
      parking_notes:'FREE public lots available on Highland. Please note parking will be limited if a concert is going on.',
       tours:'',
       direction_notes:'',
        special_closure:'',
       event_notes:'',
   },

{name:'Homestead Museum',
 address:'15415 East Don Julian Road, City of Industry, CA 91745', 
  description:"In the City of Industry, this historic site features two homes dating from the 1840s and 1920s, and a private cemetery. PLEASE NOTE: The only way to visit the museum's historic houses is on a guided tour. Guided tours are offered Wednesday through Sunday at 1:00, 2:00, 3:00, and 4:00 p.m. El Campo Santo and the Homestead Museum Gallery (where visitors will find small exhibits on display throughout the year) are self-guided experiences and open Monday through Friday from 9:00 a.m. to 5:00 p.m., and Saturday and Sunday from 12:00 to 5:00 p.m.",
   website:'www.homesteadmuseum.org/',
    phone:'(626) 968-8492',
     free_parking:'1',
      parking_notes:'n/a',
       tours:'Free guided tours are available Wednesday through Sunday.',
       direction_notes:'',
        special_closure:'',
       event_notes:'',
   },

{name:'Annenberg Space for Photography',
 address:'2000 Avenue of the Stars, Los Angeles, CA 90067', 
  description:'Nestled within the Century Park office complex, inside the former Shubert Theatre space, these galleries are dedicated to celebrating both digital and print photography. Most visitors find an hour or two provides just the right amount of time to take in all that the galleries have to offer, but the building faces a beautiful grassy knoll, perfect for dining outdoors or soaking in some Los Angeles sunshine.',
   website:'http://www.annenbergspaceforphotography.org/',
    phone:'(213) 403-3000',
     free_parking:'1',
      parking_notes:'Validated self-parking is $3.50 for three hours in the garage directly beneath the building, Wednesday through Friday before 4:30pm. After 4:30PM and all day on Saturday and Sunday, parking is a flat rate of $1.00 with validation. Please bring your parking garage ticket with you to the Space in order to have it validated by our staff.',
       tours:'',
       direction_notes:'',
        special_closure:'', event_notes:'Reopens June 1st. Skylight Studios still open.'
   },

{name:'The Paley Center for Media', address:'465 N Beverly Dr, Beverly Hills, CA 90210', 
description:'More than just a museum, the Paley Center is an institution dedicated to educating the public and exploring the intersection between media and society. It leads discussions about television, radio and emerging platforms, and the cultural, creative and social significance of these expressions.',
 website:'http://www.paleycenter.org/' ,
  phone:'(310) 786-1000',
   free_parking:'0' ,
    parking_notes:"FREE parking is available in the Paley Center parking lot located off S. Santa Monica Blvd." ,
     tours:"Guided tours, which include information on the Paley Center's history, collection, and current programs, are offered to the general public. Please inquire at the front desk for details. - See more at: http://www.paleycenter.org/visit-visitla#sthash.JUE6jUE7.dpuf",
     direction_notes:"The Paley Center is on the corner of N. Beverly Dr. and S. Santa Monica Blvd.",
      special_closure:'',
     event_notes:''
 },

{name:'RedCat',
 address:'631 West 2nd Street, Los Angeles, CA 90012', 
  description:'REDCAT is an interdisciplinary contemporary arts center for innovative visual, performing and media arts located in downtown Los Angeles inside the Walt Disney Concert Hall complex. Each season REDCAT presents a far-reaching roster of work by globally renowned artists, inside one of the most versatile and technologically advanced presentation spaces in the world.' ,website:'http://www.redcat.org/visit/hours-location',
   phone:'(213) 237-2800',
    free_parking:'1',
     parking_notes:'Parking is available in the Walt Disney Concert Hall parking garage. Enter from 2nd St. and proceed to level P3 for direct access to REDCAT. The evening event rate Monday - Friday is $9 after 4pm, $5 after 8pm. $9 flat rate on weekends. The maximum daytime rate prior to 4pm is $20.',
      tours:'',
      direction_notes:'REDCAT is located at 631 West 2nd Street, Los Angeles, CA 90012 in the heart of downtown Los Angeles on the northeast corner of the intersection of W. 2nd and Hope Streets. Housed in the Walt Disney Concert Hall complex, REDCAT has its own street entrance on 2nd Street.',
       special_closure:'', event_notes:"Barnsdall Park itself is open longer (5 am - 10 pm daily). Barnsdall Park also hosts a weekly farmer's market."
   },

{name:'Barnsdall Art Park Gallery',
 address:'4800 Hollywood Blvd, Los Angeles, CA 90027', 
  description:'Barnsdall Art Park is an art gallery and park that sits on 11 acres in the Los Feliz/Hollywood area. The site was deeded to the city of Los Angeles in 1927 as a cultural art center.',
   website:'http://www.barnsdall.org/visit/',
    phone:'(323) 644-6275',
     free_parking:'0',
      parking_notes:'FREE parking available!',
       tours:'',
       direction_notes:'',
        special_closure:'',
       event_notes:'',
   },

{name:'MOCA Geffen Contemporary',
 address:'152 NORTH CENTRAL AVENUE, LOS ANGELES, CA 90012', 
  description:'A former police car warehouse in Little Tokyo renovated by the noted California architect Frank O. Gehry, The Geffen Contemporary at MOCA (formerly The Temporary Contemporary) opened in 1983. This location offers 40,000 square feet of exhibition space and a branch of the MOCA Store.' ,
   website:'http://www.moca.org/museum/moca_geffen.php',
    phone:'(213) 626-6222',
     free_parking:'1',
      parking_notes:'Street parking recommended. Advanced Parking System lot located on the corner of 1st Street and Central Avenue, $6.50 flat rate seven days a week (prices subject to change).',
       tours:'',
       direction_notes:'More more details on how to get there, please visit:  http://www.moca.org/pdf/Parking_directions_GC.pdf',
        special_closure:'',
       event_notes:'',
   },

{name:'MOCA Pacific Design Center',
 address:'8687 MELROSE AVENUE, WEST HOLLYWOOD, CA 90069', 
  description:"Located in the heart of West Hollywood, MOCA Pacific Design Center features rotating exhibitions of architecture and design and specialty shopping at the MOCA Store. The art gallery itself is small, but while you're there check out the Pacific Design Center. PDC showcases top art, furniture, and design galleries.",
   website:'http://www.moca.org/museum/moca_pdc.php',
    phone:'(213) 621-1741',
     free_parking:'1',
      parking_notes:"Street parking is available in the neighborhood directly south of the Pacific Design Center. Please be sure to check parking signs! Metered street parking is also generally available.",
       tours:'',
       direction_notes:'More more details on how to get there, please visit: http://www.moca.org/pdf/Parking_directions_PDC.pdf',
        special_closure:'',
       event_notes:'',
   },

{name:'Historic Southwest Museum Mt. Washington Campus',
 address:'234 Museum Drive, Los Angeles, CA 90065', 
  description:'The historic Southwest Museum Mt. Washington Campus showcases rare ceramics and archeological artifacts. It is the site of the ongoing conservation initiative of the Southwest Museum collection.',
   website:'http://theautry.org/mt-washington',
    phone:'(323) 221-2164',
     free_parking:'0',
      parking_notes:"n/a" ,
       tours:'',
       direction_notes:'',
        special_closure:'',
       event_notes:'',
   },

{name:'Skylight Studios',
 address:'2000 Avenue of the Stars, Los Angeles, CA 90067', 
  description:"The Annenberg Space for Photography Skylight Studios offers FREE photography galleries, FREE lectures, and FREE film screenings. The Studios is a 5,000-square-foot multimedia studio located directly across the park from the Photography Space. Skylight Studios provides an enhanced lecture viewing atmosphere and experience through state-of-the-art A/V equipment, a concert-quality audio system and HD broadcast capabilities. Most visitors find an hour or two provides just the right amount of time to take in all that the galleries have to offer, but the building faces a beautiful grassy knoll, perfect for dining outdoors or soaking in some Los Angeles sunshine.",
   website: "http://www.annenbergspaceforphotography.org/about/visiting-the-space/hours",
    phone:'(213) 403-3000',
     free_parking:'1',
      parking_notes: "Parking validation is available and no registration is required to attend",
       tours:'',
       direction_notes:'',
        special_closure:'',
       event_notes:'',
   },

{name:'Sonos Studio',
 address:'145 N La Brea Ave, Los Angeles, CA 90036', 
  description:"The Sonos Studio is an acoustically-designed space that celebrates music listening. The Studio explores the intersection of music, art and technology through creative collaboration by hosting exhibitions, intimate concerts, listening parties, film screenings, lectures, workshops and more." ,
   website:'http://www.sonos-studio.com/Home/About',
    phone:'STUDIO@SONOS.COM',
     free_parking:'0' ,
      parking_notes:'Street parking.' ,
       tours:'',
       direction_notes:'',
        special_closure:'', event_notes:"Also have free music events with an open bar! Sign up for their newsletter"
   },

{name:'Skirball Cultural Center',
 address:'2701 N Sepulveda Blvd, Los Angeles, CA 90049', 
  description:"What's waiting for you at the Skirball Cultural Center? Art and music, history and learning, and fun for all ages! The Skirball Cultural Center is an educational institution devoted to sustaining Jewish heritage and American democratic ideals.",
   website:'http://www.skirball.org/general-info/plan-your-visit',
    phone:'(310) 440-4500',
     free_parking:'0' ,
      parking_notes:'FREE parking (except during Sunset Concerts); street parking strictly prohibited',
       tours:'',
       direction_notes:'Exit 405 Freeway at Skirball Ctr Dr. (Stay up-to-date on the I-405 Sepulveda Pass Project here.)',
        special_closure:'Closed on major Jewish holidays, Jan first, July fourth, Thanksgiving, Christmas.', event_notes: "FREE admission to visit the Skirball Cultural Center campus and view Ruby Gallery exhibitions. The Skirball features an extraordinary museum; changing exhibitions; engaging music, theater, comedy, film, family, and literary programs; Zeidlers Café; Audreys Museum Store; and a family destination inspired by the Noahs Ark story—all in a stunning architectural setting designed by renowned architect Moshe Safdie. They may be coming to enjoy an exhibition, attend a music program, participate in a meeting hosted by a community organization, and educational institution. The Skirballs core exhibition, Visions and Values: Jewish Life from Antiquity to America, traces the experiences and accomplishments of the Jewish people over four thousand years. The galleries include multimedia installations, rare artifacts, photographs, interactive computer stations, and sound recordings that lead visitors on the Jewish peoples journey, culminating with their history in the United States."
   },

{name:'Pasadena Museum of California Art',
 address:'490 E Union St, Pasadena, CA 91101', 
  description: 'PMCA is an art museum located in Pasadena showcasing art and design that originates from California.',
   website:'http://www.pmcaonline.org/planning-your-visit.html',
    phone:'(626) 568-3665',
     free_parking:'0',
      parking_notes:'FREE parking is available on the ground level of the museum and additional public parking is available across the street on Union.',
       tours:'',
       direction_notes:'The museum is located one block north of Colorado Blvd. between Los Robles Ave. and Oakland Ave.', special_closure:'',
       event_notes:'',
   }
=begin
  { name: 'UCLA Fowler Museum at UCLA', city:'Los Angeles},
  { name: 'Griffith Observatory', city: 'Los Angeles'},
  { name:   'J. Paul Getty Museum', city: 'Los Angeles'},
  { name:   'J. Paul Getty Villa', city: 'Los Angeles'},
  { name:   'UCLA Hammer Museum ', city: 'Los Angeles'},
  { name:   'The Huntington Library, Art Collections, and Botanical Gardens', city: 'Los Angeles'},
  { name:   'Japanese American National Museum', city: 'Los Angeles'},
  { name:   'LACMA', city: 'Los Angeles'},
  { name:   'Los Angeles Museum of the Holocaust', city: 'Los Angeles'},
  { name:   'Museum of Contemporary Art, Los Angeles', city: 'Los Angeles'},
  { name:   'Natural History Museum of Los Angeles County', city: 'Los Angeles'},
  { name:   'Norton Simon Museum', city: 'Los Angeles'},
  { name:   'USC Pacific Asia Museum', city: 'Los Angeles'},
  { name:   'Page Museum La Brea Tar Pits', city: 'Los Angeles'},
  { name:   'Santa Monica Museum of Art', city: 'Los Angeles'},
  { name:   'Travel Town Museum', city: 'Los Angeles'},
  { name:   'USC Fisher Museum of Art', city: 'Los Angeles'},
  { name:   'UCLA Meteorite Gallery', city: 'Los Angeles'},
  { name:   'Banning Residence Museum', city: 'Los Angeles'},
  { name:   'Hollywood Bowl Museum', city: 'Los Angeles'},
  { name:   'Homestead Museum', city: 'Los Angeles'},
  { name:   'Annenberg Space for Photography', city: 'Los Angeles'},
  { name:   'The Paley Center for Media', city: 'Los Angeles'},
  { name:   'The Fashion Institute of Design & Merchandising', city: 'Los Angeles'},
  { name:   'RedCat', city: 'Los Angeles'},
  { name:   'Barnsdall Art Park Gallery', city: 'Los Angeles'},
  { name:   'MOCA Geffen Contemporary', city: 'Los Angeles'},
  { name:   'MOCA Pacific Design Center', city: 'Los Angeles'},
  { name:   'Historic Southwest Museum Mt. Washington Campus', city: 'Los Angeles'},
  { name:   'Skylight Studios', city: 'Los Angeles'},
  { name:   'Sonos Studio', city: 'Los Angeles'}
=end
  ])

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago '}, { name: 'Copenhagen '}])
#   Mayor.create(name: 'Emanuel', city: cities.first)
